/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.House;
import model.PatientDetails;
import model.SystemAdmin;
import validators.NumberValidator;
import validators.StringValidator;

/**
 *
 * @author zainabkhokawala
 */
public class ViewPatient extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatient
     */
    public ViewPatient() {
        initComponents();
        populateTable();
          genderButtonGroup.add(male);
                genderButtonGroup.add(female);

        genderButtonGroup.add(nonBinary);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        lblSSN = new javax.swing.JLabel();
        nonBinary = new javax.swing.JRadioButton();
        lblPhoneNumber = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        lblGender = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        lblHouseNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtHouseNumber = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txtSSN = new javax.swing.JTextField();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewPatients = new javax.swing.JTable();
        lblPatientView = new javax.swing.JLabel();
        lblPatientList1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblZipCode = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        txtStreetAddress = new javax.swing.JTextField();
        lblStreetAdd = new javax.swing.JLabel();

        setLocation(new java.awt.Point(1000, 900));
        setMaximumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        lblSSN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSSN.setText("SSN");

        nonBinary.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nonBinary.setText("Non Binary");

        lblPhoneNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhoneNumber.setText("Phone Number");

        female.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        female.setText("Female");

        lblGender.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGender.setText("Gender");

        male.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        male.setText("Male");

        lblHouseNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHouseNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblHouseNumber.setText("House Number");

        txtPhoneNumber.setInputVerifier(new NumberValidator());

        lblUserName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUserName.setText("User Name");

        txtUserName.setEditable(false);
        txtUserName.setInputVerifier(new StringValidator());

        txtHouseNumber.setInputVerifier(new NumberValidator());

        btnUpdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtSSN.setInputVerifier(new NumberValidator());

        lblFullName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFullName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFullName.setText("Full Name");

        txtFullName.setInputVerifier(new StringValidator());

        lblAge.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAge.setText("Age");

        txtAge.setInputVerifier(new NumberValidator());

        tblViewPatients.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));
        tblViewPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Full Name", "Gender", "Age", "Phone Number", "House Number", "Street Address", "Zip Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Integer.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewPatients);

        lblPatientView.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lblPatientView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientView.setText("View Patient");
        lblPatientView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblPatientList1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPatientList1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientList1.setText("Patient List");
        lblPatientList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnView.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblZipCode.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblZipCode.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblZipCode.setText("Zip Code");

        txtZipCode.setInputVerifier(new NumberValidator());

        txtStreetAddress.setInputVerifier(new StringValidator());

        lblStreetAdd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblStreetAdd.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStreetAdd.setText("Street Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPatientView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(female)
                            .addGap(41, 41, 41)
                            .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(nonBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtSSN, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFullName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUserName)
                        .addComponent(txtHouseNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addComponent(lblPatientList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPatientView, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(nonBinary)
                    .addComponent(female)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(lblPatientList1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selected = tblViewPatients.getSelectedRow();
        
          if (selected < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view!");
            return;
        }
        
        PatientDetails patient = SystemAdmin.patientDirectoryRef.getPatientDirectory().get(selected);
        
        txtSSN.setText(String.valueOf(patient.getPersonSSN()));
        txtFullName.setText(String.valueOf(patient.getPersonFullName()));
        txtAge.setText(String.valueOf(patient.getPersonAge()));
        String personGender = patient.getPersonGender();
        if(personGender.equals("Female")){
            female.setSelected(true);
            male.setSelected(false);
            nonBinary.setSelected(false);
        } else if (personGender.equals("Male")){
        male.setSelected(true);
        female.setSelected(false);
            nonBinary.setSelected(false);
    } else {
            nonBinary.setSelected(true);
            male.setSelected(false);
            female.setSelected(false);
        }
        txtPhoneNumber.setText(String.valueOf(patient.getPersonPhoneNumber()));
        txtHouseNumber.setText(String.valueOf(patient.getHouse().getHouseNumber()));
        txtStreetAddress.setText(String.valueOf(patient.getHouse().getStreetAddress()));
        txtZipCode.setText(String.valueOf(patient.getHouse().getHouseZip()));
        txtUserName.setText(String.valueOf(patient.getUserName()));
        btnDelete.setEnabled(true);
        btnUpdate.setEnabled(true);
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selected = tblViewPatients.getSelectedRow();
        
        if (selected < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete!");
            return;
        }
        
        PatientDetails patient = SystemAdmin.patientDirectoryRef.getPatientDirectory().get(selected);
        
        SystemAdmin.patientDirectoryRef.getPatientDirectory().remove(patient);
        SystemAdmin.personDirectoryRef.getPersonDirectory().remove(patient);
        
        populateTable();
        
        txtSSN.setText("");
        txtFullName.setText("");
        txtAge.setText("");
        genderButtonGroup.clearSelection();
        txtPhoneNumber.setText("");
        txtHouseNumber.setText("");
        txtStreetAddress.setText("");
        txtZipCode.setText("");
        txtUserName.setText("");
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selected = tblViewPatients.getSelectedRow();
        
        if (selected < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to update!");
            return;
        }
        
        long patientSSN = Long.parseLong(txtSSN.getText());
        String patientFullName = txtFullName.getText();
        int patientAge = Integer.parseInt(txtAge.getText());
        String patientGender="";
        if(male.isSelected()){
            patientGender = "Male";
            
        } else if(female.isSelected()){
            patientGender = "Female";
            
        } else {
            patientGender = "Non Binary";
            
        }
        long patientPhone = Long.parseLong(txtPhoneNumber.getText());
        
        int houseNumber = Integer.parseInt(txtHouseNumber.getText());
        
        long houseZip = Long.parseLong(txtZipCode.getText());
        
        String patientAddress = txtStreetAddress.getText();
        
        House house = new House(patientAddress, houseNumber, houseZip);
        String patientUserName = txtUserName.getText();
        
        PatientDetails patient = SystemAdmin.patientDirectoryRef.getPatientDirectory().get(selected);
        
        
        patient.setPersonSSN(patientSSN);
        patient.setPersonFullName(patientFullName);
        patient.setPersonAge(patientAge);
        patient.setPersonGender(patientGender);   
        patient.setPersonPhoneNumber(patientPhone);
        patient.setHouse(house);
        patient.setUserName(patientUserName);
        
          populateTable();
          
        txtSSN.setText("");
        txtFullName.setText("");
        txtAge.setText("");
        genderButtonGroup.clearSelection();
        txtPhoneNumber.setText("");
        txtHouseNumber.setText("");
        txtStreetAddress.setText("");
        txtZipCode.setText("");
        txtUserName.setText("");
        
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHouseNumber;
    private javax.swing.JLabel lblPatientList1;
    private javax.swing.JLabel lblPatientView;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblStreetAdd;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton nonBinary;
    private javax.swing.JTable tblViewPatients;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtHouseNumber;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblViewPatients.getModel();
        model.setRowCount(0);
                for (PatientDetails patientDetails : SystemAdmin.patientDirectoryRef.getPatientDirectory()) {

            Object[] rowData = new Object[7];
            rowData[0] = patientDetails.getPersonFullName();
            rowData[1] = patientDetails.getPersonAge();
            rowData[2] = patientDetails.getPersonGender();
            rowData[3] = patientDetails.getPersonPhoneNumber();
            rowData[4] = patientDetails.getHouse().getHouseNumber();
            rowData[5] = patientDetails.getHouse().getStreetAddress();
            rowData[6] = patientDetails.getHouse().getHouseZip();
            model.addRow(rowData);

        }
    }
}
